# Copyright 2019, Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM python:3.6.5-stretch

WORKDIR /app

ENV PYTHONUNBUFFERED yep

RUN \
    apt-get update && \
    apt-get install vim --yes

RUN \
    pip install -U pip && \
    pip install google-api-core==1.8.2 && \
    pip install google-api-python-client==1.7.8 && \
    pip install google-cloud-pubsub==0.40.0

RUN mkdir ./logs
COPY precise-truck-742-4f10d4d14572.json ./
COPY publish_test.py ./

ENV GOOGLE_CLOUD_PROJECT precise-truck-742
ENV GOOGLE_APPLICATION_CREDENTIALS precise-truck-742-4f10d4d14572.json


CMD ["python", "publish_test.py"]
